// Lazy loader for the pretrained GloVe word embeddings (generated by
// scripts/gen-embeddings-data.mjs — int8 .bin + word list in public/vla/).
// Fetched once, in parallel with the tfjs import, during the trainer's
// "Loading" phase (~1MB — the tfjs bundle it rides along with is similar).
//
// The dequantized matrix seeds the model's FROZEN text_embedding layer and
// backs infer.ts's tokenAttention() reads (surfaced as the core's
// attentionWeights(); CPU-side — no GPU sync needed for
// a frozen table). Loading also registers the full 20k-word list with
// examples.ts's tokenizer, widening it beyond the bundled CORE_VOCAB grammar
// words — that's what lets user-typed near-synonyms ("gold", "violet") hit a
// pretrained vector instead of <unk> in try-it mode.

import { EMBED_DIM, EMBED_SCALES, VOCAB_SIZE } from "./vocab.gen";
import { registerFullVocab } from "./examples";

let matrix: Float32Array | null = null;
let words: string[] | null = null;
let loading: Promise<Float32Array> | null = null;

/** The dequantized [VOCAB_SIZE, EMBED_DIM] table, or null before load. */
export function embeddingMatrix(): Float32Array | null {
  return matrix;
}

/** The fetched word list (row order), or null before load. The trainer worker
    posts this back to the main thread, whose examples.ts tokenizer instance
    otherwise never sees registerFullVocab (module state isn't shared across
    threads) — without it, user-typed near-synonyms would tokenize to <unk>. */
export function vocabWords(): string[] | null {
  return words;
}

/**
 * Fail loudly when the fetched assets don't describe the same table the
 * compiled-in constants (vocab.gen.ts) claim.
 *
 * A host can serve a DIFFERENT generation of the assets than the JS consuming
 * them — a stale CDN copy, an unversioned asset path outliving a redeploy — and
 * the dequantize loop below would not notice: reads past the end of `bin` yield
 * `undefined → NaN`, and writes past the end of `m` are silently DISCARDED
 * (TypedArray out-of-bounds writes don't throw). The result is a frozen
 * text_embedding layer full of garbage, a model that quietly fails to learn,
 * and no error anywhere. Three comparisons buy that whole class of bug.
 */
function assertAssetShape(bin: Int8Array, list: string[], assetBase: string) {
  const regen = "regenerate with `npm run gen:embeddings`, or point assetBase at the matching version";
  if (EMBED_SCALES.length !== EMBED_DIM)
    throw new Error(
      `mini-vla: corrupt vocab.gen.ts — EMBED_SCALES has ${EMBED_SCALES.length} ` +
        `entries, expected EMBED_DIM=${EMBED_DIM}`
    );
  if (list.length !== VOCAB_SIZE - 2)
    throw new Error(
      `mini-vla: ${assetBase}/vocab.txt has ${list.length} words, expected ` +
        `${VOCAB_SIZE - 2} (VOCAB_SIZE=${VOCAB_SIZE} less <pad> and <unk>) — ${regen}`
    );
  if (bin.length !== list.length * EMBED_DIM)
    throw new Error(
      `mini-vla: ${assetBase}/embeddings-50d.bin is ${bin.length} bytes, expected ` +
        `${list.length * EMBED_DIM} (${list.length} words × EMBED_DIM=${EMBED_DIM}) — ${regen}`
    );
}

/** Fetch + dequantize (idempotent; concurrent callers share one promise).
    `assetBase` locates the generated `embeddings-50d.bin` + `vocab.txt` — the
    package's own demo/eval/test pages serve assets/ at the default `/vla`, so
    they need zero wiring; a host that version-stamps its asset directory passes
    its own base (see VLATrainer's constructor). Rejects — loudly — if what it
    fetched doesn't match this build's constants. */
export function loadEmbeddings({
  assetBase = "/vla",
}: { assetBase?: string } = {}): Promise<Float32Array> {
  if (loading) return loading;
  loading = (async () => {
    const [binRes, wordsRes] = await Promise.all([
      fetch(`${assetBase}/embeddings-50d.bin`),
      fetch(`${assetBase}/vocab.txt`),
    ]);
    if (!binRes.ok || !wordsRes.ok)
      throw new Error("embedding assets failed to load");
    const bin = new Int8Array(await binRes.arrayBuffer());
    const list = (await wordsRes.text()).split("\n").filter(Boolean);

    assertAssetShape(bin, list, assetBase);

    // rows 0 (<pad>) and 1 (<unk>) stay zero: dropped-out or unknown words
    // contribute nothing to the mean-pooled sentence vector
    const m = new Float32Array(VOCAB_SIZE * EMBED_DIM);
    for (let i = 0; i < list.length; i++)
      for (let d = 0; d < EMBED_DIM; d++)
        m[(i + 2) * EMBED_DIM + d] = bin[i * EMBED_DIM + d] * EMBED_SCALES[d];

    registerFullVocab(list);
    matrix = m;
    words = list;
    return m;
  })();
  // allow a retry after a failed fetch instead of caching the rejection
  loading.catch(() => {
    loading = null;
  });
  return loading;
}
