# Loader for the pretrained GloVe word embeddings (int8 .bin + word list in
# assets/, generated by js/scripts/gen-embeddings-data.mjs). Python port of
# js/src/embeddings.ts — here a synchronous file read rather than a lazy fetch.
#
# The dequantized matrix seeds the model's FROZEN text_embedding layer and backs
# trainer.attention_weights() reads (CPU-side — no device sync for a frozen
# table). Loading also registers the full 20k-word list with task.tokenize(),
# widening it beyond the bundled CORE_VOCAB grammar words — that's what lets
# user-typed near-synonyms ("gold", "violet") hit a pretrained vector instead of
# <unk>.

from __future__ import annotations

from pathlib import Path
from typing import Optional

import numpy as np

from .task import register_full_vocab
from .vocab_gen import EMBED_DIM, EMBED_SCALES, VOCAB_SIZE

_ASSETS = Path(__file__).resolve().parent.parent / "assets"

_matrix: Optional[np.ndarray] = None
_words: Optional[list[str]] = None


def embedding_matrix() -> Optional[np.ndarray]:
    """The dequantized [VOCAB_SIZE, EMBED_DIM] float32 table, or None before load."""
    return _matrix


def vocab_words() -> Optional[list[str]]:
    return _words


def _assert_asset_shape(raw: np.ndarray, words: list[str], base: Path) -> None:
    """Fail loudly when assets/ doesn't describe the same table vocab_gen.py's
    compiled-in constants claim — mirrors js/src/embeddings.ts's
    assertAssetShape. Without this, a stale/mismatched-but-similarly-sized
    embeddings-50d.bin + vocab.txt pair reshapes and dequantizes without error
    (numpy only raises if the total element count disagrees, not if a
    per-word/per-dim split is wrong), silently seeding the frozen
    text_embedding layer with garbage."""
    regen = "regenerate with `npm run gen:embeddings`"
    if len(EMBED_SCALES) != EMBED_DIM:
        raise ValueError(
            f"mini-vla: corrupt vocab_gen.py — EMBED_SCALES has {len(EMBED_SCALES)} "
            f"entries, expected EMBED_DIM={EMBED_DIM}"
        )
    if len(words) != VOCAB_SIZE - 2:
        raise ValueError(
            f"mini-vla: {base}/vocab.txt has {len(words)} words, expected "
            f"{VOCAB_SIZE - 2} (VOCAB_SIZE={VOCAB_SIZE} less <pad> and <unk>) — {regen}"
        )
    if raw.size != len(words) * EMBED_DIM:
        raise ValueError(
            f"mini-vla: {base}/embeddings-50d.bin is {raw.size} bytes, expected "
            f"{len(words) * EMBED_DIM} ({len(words)} words × EMBED_DIM={EMBED_DIM}) — {regen}"
        )


def load(assets_dir: Optional[Path] = None) -> np.ndarray:
    """Read + dequantize the embeddings (idempotent). Returns the frozen matrix
    and registers the full vocab with the tokenizer as a side effect."""
    global _matrix, _words
    if _matrix is not None:
        return _matrix

    base = Path(assets_dir) if assets_dir is not None else _ASSETS
    raw = np.fromfile(base / "embeddings-50d.bin", dtype=np.int8)
    words = [w for w in (base / "vocab.txt").read_text().split("\n") if w]
    _assert_asset_shape(raw, words, base)

    n = len(words)
    rows = raw.reshape(n, EMBED_DIM).astype(np.float32) * np.asarray(
        EMBED_SCALES, dtype=np.float32
    )
    # rows 0 (<pad>) and 1 (<unk>) stay zero: dropped-out or unknown words
    # contribute nothing to the attention-pooled sentence vector
    m = np.zeros((VOCAB_SIZE, EMBED_DIM), dtype=np.float32)
    m[2 : 2 + n] = rows

    register_full_vocab(words)
    _matrix = m
    _words = words
    return m
